In [24]:
import numpy as numpy
import pandas as pd

In [25]:
df=pd.read_csv("D:/EVELATE_LAS_INTERSHIP/DAY 1 WORK Data Cleaning and Preprocessing  29-MAY-2026/customer_churn_with_dates.csv")

In [26]:
df

,customerID,Date,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,26-12-2024,Female,0,Yes,No,1,No,No phone service,DSL,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,24-11-2024,Male,0,No,No,34,Yes,No,DSL,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,23-06-2024,Male,0,No,No,2,Yes,No,DSL,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,28-04-2025,Male,0,No,No,45,No,No phone service,DSL,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,17-09-2025,Female,0,No,No,2,Yes,No,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,17-06-2025,Male,0,Yes,Yes,24,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,08-01-2024,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,03-05-2025,Female,0,Yes,Yes,11,No,No phone service,DSL,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,10-08-2024,Male,1,Yes,No,4,Yes,Yes,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,20-07-2025,Male,0,No,No,66,Yes,No,Fiber optic,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   Date              7043 non-null   object
 2   gender            7043 non-null   object
 3   SeniorCitizen     7043 non-null   int64
 4   Partner           7043 non-null   object
 5   Dependents        7043 non-null   object
 6   tenure            7043 non-null   int64
 7   PhoneService      7043 non-null   object
 8   MultipleLines     7043 non-null   object
 9   InternetService   7043 non-null   object
 10  OnlineSecurity    7043 non-null   object
 11  OnlineBackup      7043 non-null   object
 12  DeviceProtection  7043 non-null   object
 13  TechSupport       7043 non-null   object
 14  StreamingTV       7043 non-null   object
 15  StreamingMovies   7043 non-null   object
 16  Contract          7043 non-null   object
 17  PaperlessBilling  7043 non-null   object
 18  PaymentMethod     7043 non-null   object
 19  MonthlyCharges    7043 non-null   float64
 20  TotalCharges      7043 non-null   object
 21  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(19)
memory usage: 1.2+ MB

Null values are missing data in a dataset.

That means some information is absent, empty, or unknown.

In [28]:
df.isnull().sum()

customerID          0
Date                0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

duplicates:Duplicate data means the same information appears more than once in a dataset.

In [29]:
df.duplicated().sum()

0

In [30]:
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [31]:
df['gender'] = df['gender'].str.lower()

In [32]:
df.columns

Index(['customerID', 'Date', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'tenure', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges',
       'Churn'],
      dtype='object')

In [33]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip().str.lower()

In [34]:
df.columns

Index(['customerID', 'Date', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'tenure', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges',
       'Churn'],
      dtype='object')

In [35]:
df

,customerID,Date,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-vhveg,26-12-2024,female,0,yes,no,1,no,no phone service,dsl,...,no,no,no,no,month-to-month,yes,electronic check,29.85,29.85,no
1,5575-gnvde,24-11-2024,male,0,no,no,34,yes,no,dsl,...,yes,no,no,no,one year,no,mailed check,56.95,1889.5,no
2,3668-qpybk,23-06-2024,male,0,no,no,2,yes,no,dsl,...,no,no,no,no,month-to-month,yes,mailed check,53.85,108.15,yes
3,7795-cfocw,28-04-2025,male,0,no,no,45,no,no phone service,dsl,...,yes,yes,no,no,one year,no,bank transfer (automatic),42.30,1840.75,no
4,9237-hqitu,17-09-2025,female,0,no,no,2,yes,no,fiber optic,...,no,no,no,no,month-to-month,yes,electronic check,70.70,151.65,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-resvb,17-06-2025,male,0,yes,yes,24,yes,yes,dsl,...,yes,yes,yes,yes,one year,yes,mailed check,84.80,1990.5,no
7039,2234-xaduh,08-01-2024,female,0,yes,yes,72,yes,yes,fiber optic,...,yes,no,yes,yes,one year,yes,credit card (automatic),103.20,7362.9,no
7040,4801-jzazl,03-05-2025,female,0,yes,yes,11,no,no phone service,dsl,...,no,no,no,no,month-to-month,yes,electronic check,29.60,346.45,no
7041,8361-ltmkd,10-08-2024,male,1,yes,no,4,yes,yes,fiber optic,...,no,no,no,no,month-to-month,yes,mailed check,74.40,306.6,yes
7042,3186-ajiek,20-07-2025,male,0,no,no,66,yes,no,fiber optic,...,yes,yes,yes,yes,two year,yes,bank transfer (automatic),105.65,6844.5,no

In [37]:
df['Date'] = pd.to_datetime(df['Date'])

C:\Users\user\AppData\Local\Temp\ipykernel_15076\2394721818.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date'] = pd.to_datetime(df['Date'])

In [40]:
df.sort_values('Date')

,customerID,Date,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3337,0840-dfezh,2024-01-01,female,0,no,no,7,yes,yes,fiber optic,...,no,no,no,no,month-to-month,yes,electronic check,75.35,564.65,no
3276,4210-qfjmf,2024-01-01,female,0,no,no,4,yes,no,fiber optic,...,no,no,no,yes,month-to-month,yes,electronic check,79.15,317.25,yes
231,3316-uwxuy,2024-01-01,male,0,no,no,50,yes,no,fiber optic,...,no,yes,no,yes,month-to-month,yes,credit card (automatic),93.50,4747.5,no
2854,4644-pizrt,2024-01-01,male,0,yes,yes,17,yes,yes,dsl,...,yes,no,yes,no,one year,yes,bank transfer (automatic),70.35,1201.65,no
885,4661-njeux,2024-01-01,male,0,no,no,1,yes,no,no,...,no internet service,no internet service,no internet service,no internet service,month-to-month,yes,mailed check,20.05,20.05,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5058,1376-hhbdv,2025-12-31,female,0,no,no,30,yes,no,dsl,...,no,no,no,no,month-to-month,yes,mailed check,48.80,1536.75,no
2484,6476-epyzr,2025-12-31,male,0,yes,yes,12,yes,no,no,...,no internet service,no internet service,no internet service,no internet service,month-to-month,no,mailed check,20.50,255.5,no
322,8705-wzcyl,2025-12-31,male,0,no,no,1,yes,no,dsl,...,no,no,no,no,month-to-month,yes,electronic check,44.80,44.8,no
6598,6169-pgncd,2025-12-31,female,0,no,no,57,yes,no,dsl,...,yes,yes,yes,no,two year,yes,credit card (automatic),74.30,4166.35,no
176,2656-fmokz,2025-12-31,female,1,no,no,15,yes,yes,fiber optic,...,no,no,no,no,month-to-month,yes,mailed check,74.45,1145.7,yes

In [41]:
df.columns = df.columns.str.lower()

In [42]:
df.columns = df.columns.str.replace(' ', '_')

In [43]:
df

,customerid,date,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-vhveg,2024-12-26,female,0,yes,no,1,no,no phone service,dsl,...,no,no,no,no,month-to-month,yes,electronic check,29.85,29.85,no
1,5575-gnvde,2024-11-24,male,0,no,no,34,yes,no,dsl,...,yes,no,no,no,one year,no,mailed check,56.95,1889.5,no
2,3668-qpybk,2024-06-23,male,0,no,no,2,yes,no,dsl,...,no,no,no,no,month-to-month,yes,mailed check,53.85,108.15,yes
3,7795-cfocw,2025-04-28,male,0,no,no,45,no,no phone service,dsl,...,yes,yes,no,no,one year,no,bank transfer (automatic),42.30,1840.75,no
4,9237-hqitu,2025-09-17,female,0,no,no,2,yes,no,fiber optic,...,no,no,no,no,month-to-month,yes,electronic check,70.70,151.65,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-resvb,2025-06-17,male,0,yes,yes,24,yes,yes,dsl,...,yes,yes,yes,yes,one year,yes,mailed check,84.80,1990.5,no
7039,2234-xaduh,2024-01-08,female,0,yes,yes,72,yes,yes,fiber optic,...,yes,no,yes,yes,one year,yes,credit card (automatic),103.20,7362.9,no
7040,4801-jzazl,2025-05-03,female,0,yes,yes,11,no,no phone service,dsl,...,no,no,no,no,month-to-month,yes,electronic check,29.60,346.45,no
7041,8361-ltmkd,2024-08-10,male,1,yes,no,4,yes,yes,fiber optic,...,no,no,no,no,month-to-month,yes,mailed check,74.40,306.6,yes
7042,3186-ajiek,2025-07-20,male,0,no,no,66,yes,no,fiber optic,...,yes,yes,yes,yes,two year,yes,bank transfer (automatic),105.65,6844.5,no

In [44]:
df.dtypes

customerid                  object
date                datetime64[ns]
gender                      object
seniorcitizen                int64
partner                     object
dependents                  object
tenure                       int64
phoneservice                object
multiplelines               object
internetservice             object
onlinesecurity              object
onlinebackup                object
deviceprotection            object
techsupport                 object
streamingtv                 object
streamingmovies             object
contract                    object
paperlessbilling            object
paymentmethod               object
monthlycharges             float64
totalcharges                object
churn                       object
dtype: object